In [3]:
#pip install numpy
import numpy as np


In [5]:
print(type([1,2,3]))

print(type((1,2,3)))


print(type(np.array((1,2,3))))
print(type(np.array([1,2,3])))

<class 'list'>
<class 'tuple'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [6]:
np.zeros([1])


array([0.])

In [7]:
np.zeros((1))

array([0.])

In [8]:
np.zeros([5,7])

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [9]:
np.zeros([6,8])

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [11]:
np.ones((4,8))

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [12]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [13]:
np.arange(12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [14]:
np.arange(4,20) #[4,20[

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [15]:
np.arange(-5)

array([], dtype=int32)

In [16]:
np.arange(-12,1)

array([-12, -11, -10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,   0])

In [22]:
arreglo_pares=np.arange(0,20,2)

In [20]:
np.arange(-12,0.5,0.5)

array([-12. , -11.5, -11. , -10.5, -10. ,  -9.5,  -9. ,  -8.5,  -8. ,
        -7.5,  -7. ,  -6.5,  -6. ,  -5.5,  -5. ,  -4.5,  -4. ,  -3.5,
        -3. ,  -2.5,  -2. ,  -1.5,  -1. ,  -0.5,   0. ])

In [25]:
print(arreglo_pares.size)
print(len(arreglo_pares))
arreglo_tres_dimen=np.zeros((2,3,4))
print(arreglo_tres_dimen.shape)

10
10
(2, 3, 4)


In [27]:
arreglo_pares.shape

(10,)

In [28]:
arreglo_pares.reshape(5,2)

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10],
       [12, 14],
       [16, 18]])

In [29]:
arreglo_pares.reshape(2,5)

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

In [32]:
arreglo_modificar=np.arange(24)

In [33]:
arreglo_modificar.reshape(6,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [34]:
arreglo_modificar.reshape(4,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [35]:
arreglo_modificar.reshape(12,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [36]:
arreglo_modificar.reshape(2,12)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [37]:
arreglo_modificar.reshape(8,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [38]:
arreglo_modificar.reshape(3,8)

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [39]:
arreglo_modificar.reshape(4,3,2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]]])

In [40]:
arreglo_modificar.reshape(3,4,2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23]]])

In [41]:
arreglo_modificar.reshape(2,3,4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [42]:
arreglo_modificar.reshape(2,4,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]])

In [43]:
arreglo_modificar.reshape(6,2,2)

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19]],

       [[20, 21],
        [22, 23]]])

In [44]:
arreglo_modificar.reshape(2,6,2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17],
        [18, 19],
        [20, 21],
        [22, 23]]])

In [45]:
arreglo_modificar.reshape(2,2,6)

array([[[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]],

       [[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]]])

In [47]:
a=np.array([10,10,10])
b=np.array([5,5,5])

In [48]:
#suma
a+b

array([15, 15, 15])

In [49]:
#resta
a-b

array([5, 5, 5])

In [50]:
#multiplicacion
a*b

array([50, 50, 50])

In [51]:
#division
a/b

array([2., 2., 2.])

In [66]:
areglo_grande=np.arange((-50,90))

TypeError: arange: scalar arguments expected instead of a tuple.

In [61]:
areglo_grande

array([-50, -49, -48, -47, -46, -45, -44, -43, -42, -41, -40, -39, -38,
       -37, -36, -35, -34, -33, -32, -31, -30, -29, -28, -27, -26, -25,
       -24, -23, -22, -21, -20, -19, -18, -17, -16, -15, -14, -13, -12,
       -11, -10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,
         2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,  14,
        15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,  27,
        28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,  40,
        41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,  53,
        54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,  66,
        67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,  79,
        80,  81,  82,  83,  84,  85,  86,  87,  88,  89])

In [64]:
areglo_grande.reshape(7,12,2)

ValueError: cannot reshape array of size 140 into shape (6,4,2)

In [65]:
#mod
a%b

array([0, 0, 0], dtype=int32)

In [72]:
#operaciones con arreglos
print(a *10)
print(a +7)
print(a -2)
print(a /9)
#print(a = 72)
print(a % 3)

[100 100 100]
[17 17 17]
[8 8 8]
[1.11111111 1.11111111 1.11111111]
[1 1 1]


In [131]:
arreglo_muestra= np.arange(20).reshape(5,2,2)

In [132]:
arreglo_muestra

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19]]])

In [106]:
arreglo_muestra

In [120]:
c=b*5
d=b*12
r=arreglo_muestra%2

In [125]:
r

array([[[0, 1],
        [0, 1]],

       [[0, 1],
        [0, 1]],

       [[0, 1],
        [0, 1]],

       [[0, 1],
        [0, 1]],

       [[0, 1],
        [0, 1]]], dtype=int32)

In [135]:
resp = (arreglo_muestra > 5) & (arreglo_muestra < 12)
arreglo_muestra[resp]

array([ 6,  7,  8,  9, 10, 11])

In [136]:
res

array([[[[[0, 1],
          [2, 3]],

         [[0, 1],
          [2, 3]]],


        [[[0, 1],
          [2, 3]],

         [[0, 1],
          [2, 3]]]],



       [[[[0, 1],
          [2, 3]],

         [[0, 1],
          [2, 3]]],


        [[[0, 1],
          [2, 3]],

         [[4, 5],
          [6, 7]]]],



       [[[[0, 1],
          [2, 3]],

         [[4, 5],
          [6, 7]]],


        [[[0, 1],
          [2, 3]],

         [[4, 5],
          [6, 7]]]],



       [[[[0, 1],
          [2, 3]],

         [[0, 1],
          [2, 3]]],


        [[[0, 1],
          [2, 3]],

         [[0, 1],
          [2, 3]]]],



       [[[[0, 1],
          [2, 3]],

         [[0, 1],
          [2, 3]]],


        [[[0, 1],
          [2, 3]],

         [[0, 1],
          [2, 3]]]]])

In [124]:
z= res < d

In [117]:
z

array([[[ True,  True],
        [ True,  True]],

       [[ True,  True],
        [ True,  True]],

       [[ True,  True],
        [ True,  True]],

       [[ True,  True],
        [ True,  True]],

       [[ True,  True],
        [ True,  True]]])

In [126]:
o= z==r

In [127]:
o

array([[[False,  True],
        [False,  True]],

       [[False,  True],
        [False,  True]],

       [[False,  True],
        [False,  True]],

       [[False,  True],
        [False,  True]],

       [[False,  True],
        [False,  True]]])

In [138]:
A= np.arange(4).reshape(2,2)
A

array([[0, 1],
       [2, 3]])

In [139]:
B= np.arange(4,8).reshape(2,2)
B

array([[4, 5],
       [6, 7]])

In [140]:
A.dot(B)

array([[ 6,  7],
       [26, 31]])

In [141]:
np.dot(A,B)

array([[ 6,  7],
       [26, 31]])

In [142]:
np.dot(B,A)

array([[10, 19],
       [14, 27]])

In [144]:
arreglo_doce= np.arange(12)
arreglo_doce

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [145]:
arreglo_doce.sum()

66

In [146]:
arreglo_doce.max()

11

In [147]:
arreglo_doce.min()

0

In [155]:
arreglo_doce.reshape(3,2,2)

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

In [149]:
arreglo_doce.sum()

66

In [156]:
arreglo_doce.reshape(3,2,2).sum(axis=0)

array([[12, 15],
       [18, 21]])

In [157]:
arreglo_doce.reshape(3,2,2).sum(axis=1)

array([[ 2,  4],
       [10, 12],
       [18, 20]])

In [158]:
arreglo_doce.reshape(3,2,2).sum(axis=2)

array([[ 1,  5],
       [ 9, 13],
       [17, 21]])