In [1]:
import numpy as np

In [3]:
arreglo_0_a_90_grados= np.array([0,30,45,60,90])
arreglo_0_a_90_grados

array([ 0, 30, 45, 60, 90])

In [4]:
radianes= arreglo_0_a_90_grados * np.pi /180
radianes

array([0.        , 0.52359878, 0.78539816, 1.04719755, 1.57079633])

In [5]:
np.sin(radianes)

array([0.        , 0.5       , 0.70710678, 0.8660254 , 1.        ])

In [6]:
np.sin(arreglo_0_a_90_grados)

array([ 0.        , -0.98803162,  0.85090352, -0.30481062,  0.89399666])

In [7]:
np.cos(radianes)

array([1.00000000e+00, 8.66025404e-01, 7.07106781e-01, 5.00000000e-01,
       6.12323400e-17])

In [8]:
np.tan(radianes)

array([0.00000000e+00, 5.77350269e-01, 1.00000000e+00, 1.73205081e+00,
       1.63312394e+16])

In [11]:
np.cos(arreglo_0_a_90_grados)


array([ 1.        ,  0.15425145,  0.52532199, -0.95241298, -0.44807362])

In [10]:
np.tan(arreglo_0_a_90_grados)

array([ 0.        , -6.4053312 ,  1.61977519,  0.32004039, -1.99520041])

In [14]:
arreglo_random = np.random.randint(10) #enteros positivos 0-9 [0-10[
arreglo_random

5

In [21]:
arreglo_random2 = np.random.randint(-1,2) #enteros positivos 0-9 
                                            #[-1-2[
arreglo_random2

1

In [22]:
arreglo_random3 = np.random.randint(
                    0, #minimo
                    11, #maximo
                    3) #numero de randomicos
                                            #[-1-2[
arreglo_random3

array([9, 7, 6])

In [23]:
arreglo_random3.mean()    #medias

7.333333333333333

In [24]:
np.median(arreglo_random3)  #medianas

7.0

In [25]:
np.std(arreglo_random3)  

1.247219128924647

In [26]:
np.var(arreglo_random3)

1.5555555555555554

In [27]:
np.mean(arreglo_random3)

7.333333333333333